    use strict;
    use warnings;
	
	# grab the current time
	#my @now = localtime();
	
	use POSIX;
	use constant DATETIME => strftime("%Y-%m-%d_%H-%M-%S", localtime);
	
	# rearrange the following to suit your stamping needs.
	# it currently generates YYYYMMDDhhmmss
	#my $timeStamp = sprintf("%04d%02d%02d%02d%02d%02d", 
    #                    $now[5]+1900, $now[4]+1, $now[3],
    #                    $now[2],      $now[1],   $now[0]);
     
    open(my $fh, '>', 'C:\justTesting\report'.DATETIME.'.txt');
    print $fh "My first report generated by perl\n";
    close $fh;
    print "done\n";